name: Build Offline Course (Docker)

on:
  workflow_dispatch:  # manual trigger

jobs:
  build-course:
    runs-on: ubuntu-22.04

    steps:
      # Checkout the repo (optional if you need local scripts)
      - name: Checkout repo
        uses: actions/checkout@v3

      # Pull the Docker image with the dev tag
      - name: Pull Docker image
        run: docker pull ghcr.io/openzim/openedx:dev

      # Run openedx2zim inside Docker
      - name: Run openedx2zim
        run: |
          mkdir -p offline_course
          docker run --rm \
            -v ${{ github.workspace }}/offline_course:/offline_course \
            ghcr.io/openzim/openedx:dev \
            openedx2zim --course-url "https://iedra.uned.es/courses/course-v1:UNED+TYEPRO+2021/course/" --email "dballeste38@alumno.uned.es" --password "cogitoergosum" --name "tyepro2021" --title "Tecnicas y Estrategias Profesionales (2021)" --description "Offline export of the UNED iedra course Tecnicas y Estrategias Profesionales 2021" --creator "UNED" --publisher "iedra.uned.es" --tags "UNED,iedra,tyepro2021,course" --output "course"
      # Upload the ZIM artifact
      - name: Upload ZIM
        uses: actions/upload-artifact@v4
        with:
          name: tyepro2021-zim
          path: offline_course/*.zim
